# Ne pas écouter sur le port standard, on passe sur le 8883 pour le TLS
listener 8883
allow_anonymous false

# Chemins vers tes certificats (générés à l'étape 1)
cafile certs/ca.crt
certfile certs/server.crt
keyfile certs/server.key

# Authentification et Droits
password_file passwd
acl_file acl
